version: "3.9"

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_DB: kerberos
    ports:
      - "5432:5432"